[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true

[buildPlans.iosevka-custom.variants.design]
e = "flat-crossbar"
f = "flat-hook"
# i = "hooky"
l = "tailed-serifed"
# r = "top-serifed"
one = "base"
two = "straight-neck"
three = "flat-top"
four = "semi-open-non-crossing"
five = "vertical-upper-left-bar"
six = "straight-bar"
eight = "two-circles"
tilde = "low"
asterisk = "penta-low"
paren = "large-contour"
brace = "curly"
number-sign = "slanted"
at = "fourfold"
dollar = "open"
percent = "rings-continuous-slash"

[buildPlans.iosevka-custom.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.iosevka-custom.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.iosevka-custom.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.iosevka-custom.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

[buildPlans.iosevka-custom.widths.normal]
shape = 500
menu = 5
css = "normal"
