[buildPlans.iosevka-custom]
family = "Iosevka Custom"
spacing = "normal"
serifs = "sans"
no-cv-ss = true
no-ligation = true

[buildPlans.iosevka-custom.variants.design]
capital-j = "serifless"
b = "toothless-corner"
d = "toothless-corner-serifless"
e = "flat-crossbar"
f = "flat-hook"
g = "double-storey"
l = "tailed-serifed"
m = "top-left-serifed"
n = "straight-top-left-serifed"
p = "motion-serifed"
q = "tailed-motion-serifed"
r = "top-serifed"
t = "standard"
u = "tailed"
w = "straight"
turn-v = "straight"
zero = "slashed"
two = "straight-neck"
three = "flat-top"
four = "semi-open-non-crossing"
five = "vertical-upper-left-bar"
six = "straight-bar"
eight = "two-circles"
tilde = "low"
asterisk = "penta-low"
caret = "medium"
paren = "large-contour"
brace = "curly"
number-sign = "upright-open"
at = "fourfold-tall"
dollar = "open"
percent = "rings-continuous-slash"
bar = "force-upright"
question = "smooth"
punctuation-dot = "round"

[buildPlans.iosevka-custom.widths.normal]
shape = 600
menu = 5
css = "normal"